[package]
name = "packet_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
af_packet="0.3.1"
num_cpus="1.8"
pktparse="0.7.1"
nom="7.1.3"
smoltcp = "0.10.0"